project.godot

Scale with window (and screen) size

---

.config/dotnet-tools.json
.editorconfig
Common/Logger.cs
Common/Singleton.cs
Common/TimeController.cs
Cycle/DayNight/ClockUi.cs
Cycle/DayNight/NightTint.cs
Cycle/Weather/WeatherCycle.cs
Cycle/Weather/WeatherCycleUi.cs
Plants/APlant.cs
Plants/IPlantable.cs
Plants/PlantController.cs
Plants/Requirement.cs
Plants/RequirementType.cs
Plants/Soil/SoilTile.cs
Player/Player.cs
Player/PlayerStateMachine.cs
Player/State.cs
Player/StateIdle.cs
Player/StateWalk.cs
README.md
ResourceData/PlantData.cs
ResourceData/RequirementData.cs
ResourceData/RequirementDataForGrowthStage.cs
ResourceData/ResourceManager.cs
TestScenes/APlant/TestAPlant.cs
TestScenes/PlantAndCycles/TestCycleWithPlants.cs

Added `csharpier` and `.editorconfig`

---

CONTRIBUTING.md
README.md

Closes #27
Added a bit of documentation directly to the repo

Add notion things

---

Entity/EntityStats.cs
Item/InteractableItem.cs

- Remove [Export] (expects read and writable field)
- Fix constructor call

[Hotfix] compile errors

---

Common/BBColor.cs
Common/Logger.cs

Adds BBCode class for common colors.
Use those colors in logger logging levels.
Add constructor which accepts a node

Add additional logger constructor and colors to log levels

---

.github/workflows/build.yml

build: only run on non-draft prs

---

NPC/VendingMachine/VendingMachineNPC.cs
project.godot

Fixes a missing impl from interface which causes compile errors

[Hotfix] Fix compile error (missing impl)

---

Main.tscn
Scenes/GUIContainer.tscn
Scenes/GameWorldContainer.tscn
project.godot

Create main scene

---

Assets/DefaultUPGTheme.tres
Scenes/GUIContainer.tscn
project.godot

- Disable dialogue UI in GUIContainer for now as it's not done yet

Create first release (v0.1.0)

---

.github/workflows/build.yml
export_presets.cfg
project.godot

Fix auto release

---

.github/workflows/build.yml
project.godot

Fix file path of automatic file uploads

---

Features/Inventory/BigInventory.cs
Features/Inventory/IInventory.cs
Features/Inventory/Inventory.cs
Features/Inventory/ItemStack.cs
Features/Shops/SeedShop.cs
Features/VendingMachine/UI/VendingMachineUI.cs
Features/VendingMachine/VendingMachine.cs
Scenes/TestScenes/VendingMachineTest/UiOnly.cs

contains changes from #63 
Early partial merge.

[Feature] Implement player inventory (item container)

---

Features/Plants/APlant.cs
Resources/Plants/Chubery/Chubery.tres
Resources/Plants/Drupoleaum/Drupoleaum.tres
Resources/Plants/Licary/Licary.tres

Data for Plants
- Chubery
- Licary
- Drupoleaum

Add Plant requirement data

---

Features/GUI/HUDs/Resources/ResourcesHUD.tscn
Main.tscn
Scenes/GUIContainer.tscn
Scenes/GameWorldContainer.tscn
Scenes/TestScenes/APlant/APlantPrefab.tscn
Scenes/TestScenes/APlant/TestAPlant.cs
Scenes/TestScenes/APlant/TestAPlant.tscn

add playtest hotfix into main pls
maybe check if gold coin icon is visible cause it wasn't in my Godot but seems like an engine restart problem

add second plant w/ soil tile and change sprite

---

Features/GUI/HUDs/MainMenu/MainMenu.tscn
Features/GUI/HUDs/SettingsMenu/Settings.tscn
project.godot

Last PR set the wrong main scene. Now properly shows main menu again.
Also adjusts main menu screen for 360p

[Hotfix] Fix incorrect main scene

---

Features/Crafting/Dehydrator/DehydratorInventoryView.tscn
Features/GUI/Book/BookView.tscn
Features/GUI/Vending/VendingGUI.tscn
Scenes/GUIContainer.tscn
Scenes/GameWorldContainer.tscn
project.godot

Fix GUI scene not auto-merging correctly (dropping the import of dehydrator scene)

[Hotfix] Broken GUI Scene

---

Common/EventBus.cs
Features/Dialogue/DialogueUI.cs
Features/Dialogue/Dialogue_Scene.tscn
Features/Dialogue/Models/DialogueLine.cs
Features/NPC/RoutinePlanner/NpcRoutinePlanner.cs

Reverts kida31/untitled-plant-game#211

Revert "[Hotfix] Fix visuals of dialogue"

---

Features/GUI/HUDs/Toolbelt/ToolBlobView.cs
Features/Player/Player.cs
Features/Tools/Data/IDisplayData.cs
Features/Tools/Data/IToolUseData.cs
Features/Tools/Data/SeedBag.tres
Features/Tools/Data/Shears.tres
Features/Tools/Data/Shovel.tres
Features/Tools/Data/ToolData.cs
Features/Tools/Data/WateringCan.tres
Features/Tools/SeedBag.cs
Features/Tools/Shears.cs
Features/Tools/Shovel.cs
Features/Tools/Tool.cs
Features/Tools/WateringCan.cs

Removes some hardcoded textures.
Will help with #256 
Makes the tool class a resource. If needed, tool variations can be more easily created, saved and swapped out.

[Refactor] Tools as resource

---

Features/Plants/Models/PlantData.cs
Features/Plants/Models/RequirementData.cs
Features/Plants/Models/RequirementDataForGrowthStage.cs
Features/Plants/Plant.cs
Features/Plants/PlantMap.cs
Features/Plants/PlantPrefab.tscn
Features/Plants/soil.tscn
Features/Tools/SeedBag.cs
Resources/Plants/Chuberry.tres
Resources/Plants/Drupoleaum.tres
Resources/Plants/Licary.tres
Scenes/GameWorldContainer.tscn
Scenes/GardenMapScene.tscn
Scenes/SoilTiles.tscn

- makes plants less complicated
-> remove days to grow, make consumption & absorption rate all the same for all stages
- add plants to scene for better gameplay
- remove decorative plants
- moves planters layer to soil tiles scene

222 plant improvements

---

Features/Plants/Plant.cs
Features/Plants/PlantMap.cs
Resources/Plants/Drupoleaum.tres
Resources/Plants/Licary.tres

Make plant map update tiles where plants die

Unalive plants

---

Resources/Tools/WateringCan.tres

[Balancing] Increase watering can channel time 0s to 0.5s

---

Features/GUI/Interactions/InteractHint.cs
Features/GUI/Interactions/InteractHint.tscn
Features/Interaction/InteractionManager.cs
Features/Interaction/InteractionManager.tscn
Features/Item/InteractableItem.cs
Features/NPC/NpcInteraction/NpcPlayerInteraction.cs

[Feature] New interact hint

---

Features/Item/Components/TagsComponent.cs
Features/Item/ItemDatabase.cs

- Adds random things as easter eggs
- Let your creativity be free

Easter Eggs

---

Features/Crafting/Dehydrator/DehydratorInventoryView.tscn
Features/GUI/Vending/VendingGUI.tscn
Features/Shops/GUI/SeedShopView.tscn
Scenes/GUIContainer.tscn

add inventory category tabs

---

Common/GameStates/GameStateMachine.cs
Common/TimeController.cs

- Add `Pause` and `Resume` function to `TimeController`
- Temporary `HandleTransition` function for GameStateMachine

Pause Time when not in freeroam state

---

Common/EventBus.cs
Features/Dialogue/Events/CameraPan.cs
Features/Dialogue/Events/CameraPan.cs.uid
Features/Player/Player.tscn
Features/Player/PlayerCamera.cs
Features/Player/PlayerCamera.cs.uid
Scenes/Godfrey.tscn

- Camera Pan Dialogue Event
- Camera will pan to given position (awkwardly but it will pan)
- Removes random walk of godfrey

341 camera pan event

---

Resources/Dialogue/SeedBoy/seed_boy_init_4.tres

switched responses
closes #340

fix switched seed boy responses

---

Common/Assert.cs
Features/GUI/Items/StorageView.cs
Features/GUI/Vending/VendingGUI.tscn
Features/GUI/Vending/VendingMachineUI.cs

- Add hardcoded navigation for scenario "withdraw button available" and "withdraw button unavailable".
- Add more default messages for assertions
Navigation without withdraw button (unavailable button)
Navigation with withdraw button
Remaining navigation stays unchanged (auto-order by godot)
Closes #329

[Bugfix] Fix vending machine navigation. Hardcode navigation

---

Resources/Dialogue/Godfrey/Tutorial/WateringTutorial.tres
Resources/Dialogue/Godfrey/Tutorial/WateringTutorial_DE.tres
Resources/Quest/IntroQuest.tres
Resources/Quest/IntroQuest_DE.tres
Resources/Quest/TutorialQuest_DE.tres

- Fixes Bug where any Dialogue would complete the Intro Questline Task (Dialogue in Task was missing)
- Adds Quest Translation in English

371 bug intro tutorial
